### ISSUE TITLE
sortedcollections

### ISSUE THREAD

**Issue by mrocklin** [conda-forge/sortedcontainers-feedstock#2]
There appears to be a sibling project, `sortedcollections` maintained by the same author.  Are any of the maintainers of this feedstock interested in also maintaining a `sortedcollections` feedstock?

**Comment by mrocklin** [comment]
cc @grantjenks

**Comment by nehaljwani** [comment]
Closing, as there is a feedstock already available at: https://github.com/conda-forge/sortedcollections-feedstock/
